/* Dados para a tabela de Empresas */

SET BLOBFILE '01dados.lob';

INSERT INTO EMPRESAS
  (PK_EMPRESAS, CNPJ_EMP, RAZ_SOC, NOM_FAN, INSCR_EST, FK_PAISES, FK_ESTADOS,
   FK_MUNICIPIOS, FK_TIPO_ENDERECOS, END_EMP, NUM_END, CMP_EMP, CEP_EMP,
   COD_ATV, TIP_EMP, FON_CMCL, FON_FAX, LOGO_EMP, QTD_TAB, FLAG_TIMG)
VALUES
  (1, '00737733000103', 'SISTEMA PROCESSA E.R.P. OPEN SOURCE', 'SISTEMA PROCESSA',
   '0560035594', 27, 'RS', 69663, NULL, 'AV. BORGES DE MEDEIROS', 3046,
   'CENTRO', 95670000, NULL, 0, '5432861154', '5432861154', :h00000000_0000197E,
   0, 2);

COMMIT WORK;

/* Dados para a tabela de Parametros Globais */
INSERT INTO PARAMETROS_GLOBAIS
  (PK_PARAMETROS_GLOBAIS, FK_CLIENTES, NUM_CAS_DEC, DIAS_ATR, PER_CVMED,
   QTD_DVMED, QTD_DCMED, QTD_DTOL, VERSAO, VER_1, VER_2, VER_3, VER_4)
VALUES
  (1, NULL, NULL, 2, 365, 30, 30, 1, '1.0.8.1', 1, 0, 8, 1);

commit work;

/* Dados da Tabela de Linguagens */
INSERT INTO LINGUAGENS
  (PK_LINGUAGENS, DSC_LANG)
VALUES
  ('pt_br', 'Português Brasil');

INSERT INTO LINGUAGENS
  (PK_LINGUAGENS, DSC_LANG)
VALUES
  ('en', 'English');

/* Dados da Tabela de Operadores */
INSERT INTO OPERADORES (PK_OPERADORES, FK_EMPRESAS, FK_CADASTROS, FK_LINGUAGENS, DSCT_MAX, SEN_NET, EMAIL_OPE, FLAG_LSEN, FLAG_BRW, FLAG_FND, FLAG_INS, FLAG_UPD, FLAG_DEL, DTHR_LOGIN) VALUES ('SYSDBA', 1, NULL, 'pt_br', 0, '0', 'alcindo@sistemaprocessa.com.br', 1, 1, 1, 1, 1, 1, NULL);
INSERT INTO OPERADORES (PK_OPERADORES, FK_EMPRESAS, FK_CADASTROS, FK_LINGUAGENS, DSCT_MAX, SEN_NET, EMAIL_OPE, FLAG_LSEN, FLAG_BRW, FLAG_FND, FLAG_INS, FLAG_UPD, FLAG_DEL, DTHR_LOGIN) VALUES ('ALCINDO', 1, NULL, 'pt_br', 0, '1', 'alcindo@sistemaprocessa.com.br', 1, 1, 1, 1, 1, 1, NULL);

/* Dados para a tabela de Parametros */
update PARAMETROS set
       DSCT_MAX = 10,
       TAX_JURM = 2,
       CUST_FIX = 5,
       MRGL_PDR = 0.5,
       FLAG_COM_TPGTO = 0,
       FLAG_COM_DESC  = 0,
       FLAG_COM_ITEM  = 0,
       FLAG_DESC_ITEM = 0
 where FK_EMPRESAS = 1;

INSERT INTO CENTRO_CUSTOS (PK_CENTRO_CUSTOS, DSC_CCST) VALUES (1, 'ADMINISTRAÇÃO');

COMMIT WORK;

/* Dados da Tabela PAISES */
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'AFRICA DO SUL', 'Africano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ALBANIA', 'Albanês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ALEMANHA', 'Alemão');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ANDORRA', 'Andorra');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ANGOLA', 'Angolano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ANGUILLA', 'Anguilla');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ANTIGUA/B', 'Antigua');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ANTILHAS', 'Antilhas');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ARABIA SAUDITA', 'Árabe');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ARGELIA', 'Argeliano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ARGENTINA', 'Argentino');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ARMENIA', 'Armeno');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ARUBA', 'Aruba');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'AUSTRALIA', 'Australiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'AUSTRIA', 'Austríaco');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'AZERBAIDJAO', 'Azerbaidjao');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BAHAMAS', 'Bahamas');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BAHRAIN', 'Bahrain');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BANGLADES', 'Banglades');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BARBADOS', 'Barbados');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BELGICA', 'Belga');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BELIZE', 'Belize');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BENIN', 'Benin');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BERMUDAS', 'Bermudas');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BIELORUSS', 'Bieloruss');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BOLIVIA', 'Boliviano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BRASIL', 'Brasileiro');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BRUNEI', 'Brunei');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'BULGARIA', 'Búlgaro');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CABO VERDE', 'Cabo Verde');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CAMAROES', 'Camarões');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CANADA', 'Canadense');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CASAQUISTAO', 'Casaquistão');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CHILE', 'Chileno');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CHINA', 'Chinês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CHIPRE', 'Chipre');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CINGAPURA', 'Cingapura');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'COLOMBIA', 'Colombiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CONGO', 'Congo');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'COREIA DO SUL', 'Coreano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'COREIA DO NORTE', 'Coreano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'COSTA DO MARFIM', 'Costa do Marfim');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'COSTA RICA', 'Costa Riquenho');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CROACIA', 'Croata');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'CUBA', 'Cubano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'DINAMARCA', 'Dinamarquês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'EGITO', 'Egípcio');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'EL SALVADOR', 'Salvadorenho');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'EMIRADOS ARABES', 'Árabe');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'EQUADOR', 'Equatoriano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ESLOVAQUIA', 'Eslovaco');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ESLOVENIA', 'Eslovenia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ESPANHA', 'Espanhol');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ESTADOS UNIDOS DA AMERICA', 'Americano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ESTONIA', 'Estonia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ETIOPIA', 'Etiopia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'FILIPINAS', 'Filipino');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'FINLANDIA', 'Finlandês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'FRANCA', 'Francês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GABAO', 'Gabao');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GANA', 'Gana');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GEORGIA', 'Georgia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GIBRALTAR', 'Gibraltar');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GRECIA', 'Grego');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GRANADA', 'Granada');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GROENLANDIA', 'Groelandia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GUADALUPE', 'Guadalupe');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GUATEMALA', 'Guatemala');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GUIANA', 'Guiana');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GUIANA FRANCESA', 'Guiana');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'GUINE-BISSAO', 'Guine-bissao');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'HAITI', 'Haitiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'HOLANDA', 'Holandês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'HONDURAS', 'Hondurenho');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'HUNGRIA', 'Húngaro');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'IEMEN', 'Iemen');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'INDIA', 'Indiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'INDONESIA', 'Indonesia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'INGLATERRA', 'Inglês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'IOGUSLAVIA', 'Iugoslavo');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'IRA', 'Iraniano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'IRAQUE', 'Iraquiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'IRLANDA', 'Irlandês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ISLANDIA', 'Islandia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ISRAEL', 'Israelita');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ITALIA', 'Italiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'JAMAICA', 'Jamaicano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'JAPAO', 'Japonês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'JORDANIA', 'Jordaniano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'KUWAIT', 'Kuwaitino');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'LETONIA', 'Letonês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'LIBANO', 'Libanês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'LIBIA', 'Libiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'LITUANIA', 'Lituania');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'LUXEMBURGO', 'Luxemburgo');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MACAU', 'Macau');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MACEDONIA', 'Macedonia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MALASIA', 'Malasia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MALAWI', 'Malawi');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MALI', 'Mali');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MALTA', 'Maltês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MARROCOS', 'Marroquino');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MARTINICA', 'Martinica');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MEXICO', 'Mexicano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MOCAMBIQUE', 'Mocambique');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MONACO', 'Monaco');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'MONTSERRAT', 'MontSerrat');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NAMIBIA', 'Namibia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NEPAL', 'Nepal');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NICARAGUA', 'Nicaragua');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NIGERIA', 'Nigeriano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NORUEGA', 'Norueguês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NOVA GUINE', 'Nova Guine');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'NOVA ZELANDIA', 'Nova Zelandia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'OMA', 'Oma');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PANAMA', 'Panamenho');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PAQUISTAO', 'Paquistanês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PARAGUAI', 'Paraguaio');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PERU', 'Peruano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'POLONIA', 'Polonês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PORTO RICO', 'Porto Riquenho');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'PORTUGAL', 'Português');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'QUIRQUISTAO', 'QUIRQUISTAO');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'REINO UNIDO', 'REINO UNIDO');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'REP. TCHECA','REP. TCHECA');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ROMENIA', 'Romeno');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'RUSSIA', 'Russo');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SAMOA AME', 'Samoa Ame');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SAMOA OCIDENTAL', 'Samoa Ocidental');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SAN MARINO', 'San Marino');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SENEGAL', 'Senegal');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SERRA LEOA', 'Serra Leoa');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SIRIA', 'Sírio');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SRI LANKA', 'Sri Lanka');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SUAZILAND', 'Suaziland');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SUDAO', 'Sudanês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SUECIA', 'Sueco');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SUICA', 'Suíço');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'SURINAME', 'Suriname');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TAILANDIA', 'Tailandês');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TAITI', 'Taitiano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TANZANIA', 'Tanzânia');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TOGO', 'Togo');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TONGA', 'Tonga');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TORTOLA', 'Tortola');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TRANSKEI', 'Transkey');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TRINIDAD', 'Trinidad');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TUNISIA', 'Tunísio');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'TURQUIA', 'Turco');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'UCRANIA', 'Ucrâniano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'UGANDA', 'Uganda');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'URUGUAI', 'Uruguaio');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'UZBEQUISTAO', 'Uzbequistao');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'VENEZUELA', 'Venezuelano');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'VIETNA', 'Vietnamita');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ZAIRE', 'Zaire');
INSERT INTO PAISES (PK_PAISES, DSC_PAIS, NAC_PAIS) VALUES (0,'ZAMBIA', 'Zambia');

COMMIT WORK;

/* Dados da Tabela ESTADOS para BRASIL */
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'AC','ACRE');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'AL','ALAGOAS');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'AM','AMAZONAS');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'AP','AMAPA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'BA','BAHIA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'CE','CEARA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'DF','DISTRITO FEDERAL');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'ES','ESPIRITO SANTO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'GO','GOIAS');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'MA','MARANHAO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'MG','MINAS GERAIS');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'MS','MATO GROSSO DO SUL');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'MT','MATO GROSSO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'PA','PARA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'PB','PARAIBA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'PE','PERNAMBUCO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'PI','PIAUI');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'PR','PARANA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'RJ','RIO DE JANEIRO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'RN','RIO GRANDE DO NORTE');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'RO','RONDONIA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'RR','RORAIMA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'RS','RIO GRANDE DO SUL');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'SC','SANTA CATARINA');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'SE','SERGIPE');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'SP','SAO PAULO');
INSERT INTO ESTADOS (FK_PAISES,PK_ESTADOS,DSC_UF) VALUES (27,'TO','TOCANTINS');

COMMIT WORK;

commit work;

/* Cria categorias defaults */
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (1, 'CLIENTES', 0);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (2, 'FORNECEDORES', 1);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (3, 'FUNCIONARIOS', 2);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (4, 'AGENTE PORTUARIO', 3);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (5, 'TRANSPORTADORAS', 1);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (6, 'VENDEDORES', 2);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (7, 'REPRESENTANTES', 2);
INSERT INTO CATEGORIAS (PK_CATEGORIAS, DSC_CAT, FLAG_CAT) VALUES (8, 'ADMINISTRACAO', 2);

COMMIT WORK;

