/******************************************************************************/
/****         Generated by IBExpert 2004.01.22 15/06/2006 02:32:00         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET BLOBFILE '05relatorios.lob';

INSERT INTO RELATORIOS (FK_LINGUAGENS, FK_MODULOS, PK_RELATORIOS, DSC_REL, DSC_GRAPH, SQL_REL, SQL_GRAPH, REL_SYS, FLAG_GRAPH, OPE_INC, DTHR_INC, OPE_ALT, DTHR_ALT) VALUES ('pt_br', 5, 1, 'Listagem de Seções, Grupos e Subgrupos', '', NULL, NULL, :h00000000_0001C4AE, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-02-14 17:50:33');
REINSERT ('pt_br', 5, 2, 'Tabela de Preços', '', NULL, NULL, :h0001C4AE_00005072, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-06-01 17:07:01');
REINSERT ('pt_br', 5, 3, 'Listagem dos Estoques', '', NULL, NULL, :h00021520_0001BE54, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-06-01 17:09:25');
REINSERT ('pt_br', 8, 1, 'Ordem de Produção', '', NULL, NULL, :h0003D374_00000505, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-02-15 16:23:58');
REINSERT ('pt_br', 1, 1, 'Listagem dos Acessos por Operador', '', NULL, NULL, :h0003D879_0001A031, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-03-09 17:48:01');
REINSERT ('pt_br', 10, 1, 'LISTAGEM DOS ÍTENS PARA PRODUÇÃO', '', NULL, NULL, :h000578AA_0001A4E8, 0, 'SYSDBA', '2006-03-09 20:42:07', NULL, NULL);
REINSERT ('pt_br', 1, 2, 'Listagem dos Programas', '', NULL, NULL, :h00071D92_0001915E, 0, 'SYSDBA', '2006-03-09 20:42:07', 'ALCINDO', '2006-03-09 17:48:42');

COMMIT WORK;

